"""
Export router — JSON, CSV, and Markdown report generation.
PDF export planned for Stage 6.
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse, JSONResponse
from pydantic import BaseModel
from typing import Any
import json, csv, io

router = APIRouter(prefix="/export", tags=["Export"])


class ExportBundle(BaseModel):
    project_id: str
    project_name: str
    diagnostic: dict[str, Any] | None = None
    syndrome: dict[str, Any] | None = None
    climate: dict[str, Any] | None = None
    pathways: dict[str, Any] | None = None
    tradeoffs: dict[str, Any] | None = None
    passports: list[dict[str, Any]] = []
    priority_index: list[dict[str, Any]] = []


@router.post("/json")
def export_json(bundle: ExportBundle) -> JSONResponse:
    return JSONResponse(content=bundle.model_dump())


@router.post("/markdown", response_class=PlainTextResponse)
def export_markdown(bundle: ExportBundle) -> str:
    lines: list[str] = [
        f"# LIRA-AI Report: {bundle.project_name}",
        f"**Project ID:** {bundle.project_id}",
        "",
    ]

    if bundle.diagnostic:
        sev = bundle.diagnostic.get("degradation_severity", "unknown")
        score = bundle.diagnostic.get("composite_health_score", "N/A")
        completeness = bundle.diagnostic.get("data_completeness_pct", "N/A")
        lines += [
            "## Landscape Diagnosis",
            f"- **Degradation severity:** {sev}",
            f"- **Composite health score:** {score}",
            f"- **Data completeness:** {completeness}%",
            "",
        ]

    if bundle.syndrome:
        primary = bundle.syndrome.get("primary_syndrome", {})
        lines += [
            "## Degradation Syndrome",
            f"- **Primary syndrome:** {primary.get('name', 'Unknown')}",
            f"- **Risk level:** {primary.get('risk_level', 'Unknown')}",
            f"- **Confidence:** {primary.get('confidence', 'Unknown')}",
            "",
            "### Causal Narrative",
            bundle.syndrome.get("causal_narrative", "Not available"),
            "",
            "### Assumptions",
        ]
        for a in bundle.syndrome.get("assumptions", []):
            lines.append(f"- {a}")
        lines.append("")

    if bundle.climate:
        lines += [
            "## Climate Futures",
            f"- **Overall climate risk score:** {bundle.climate.get('overall_climate_risk_score', 'N/A')}",
            f"- **Scenario:** {bundle.climate.get('scenario', 'N/A')}",
            f"- **Horizon:** {bundle.climate.get('horizon', 'N/A')}",
            "",
            bundle.climate.get("summary_narrative", ""),
            "",
        ]

    if bundle.pathways:
        recommended = bundle.pathways.get("recommended_primary", "")
        lines += [
            "## Regeneration Pathways",
            f"- **Recommended primary pathway:** {recommended}",
            f"- **Rationale:** {bundle.pathways.get('rationale', '')}",
            "",
        ]
        for pw in bundle.pathways.get("pathways", []):
            lines.append(f"### {pw.get('pathway_type', '').replace('_', ' ').title()} Pathway")
            lines.append(f"*{pw.get('why_it_fits', '')}*")
            lines.append("")
            lines.append("**Recommended package:**")
            for opt in pw.get("recommended_package", []):
                lines.append(f"- {opt.get('option_name', '')}")
            lines.append("")

    if bundle.passports:
        lines.append("## Investment Passports")
        for p in bundle.passports:
            lines += [
                f"### {p.get('package_name', '')}",
                f"- **Target geography:** {p.get('target_geography', '')}",
                f"- **Investment readiness:** {p.get('investment_readiness_score', 'N/A')}",
                f"- **Climate robustness:** {p.get('climate_robustness_score', 'N/A')}",
                f"- **Problem diagnosis:** {p.get('problem_diagnosis', '')}",
                "",
                "**Maladaptation alerts:**",
            ]
            for alert in p.get("maladaptation_alerts", []):
                lines.append(f"- {alert}")
            lines.append("")

    lines += [
        "---",
        "*Generated by LIRA-AI — Landscape Futures Lab MVP*",
        "*All assumptions and data gaps are explicitly flagged. Field validation required before investment decisions.*",
    ]

    return "\n".join(lines)


@router.post("/csv-priority")
def export_priority_csv(bundle: ExportBundle) -> PlainTextResponse:
    if not bundle.priority_index:
        raise HTTPException(status_code=400, detail="No priority index data in bundle")

    output = io.StringIO()
    fieldnames = ["package_name", "weighted_score", "rank", "explanation"]
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for row in bundle.priority_index:
        writer.writerow({
            "package_name": row.get("package_name", ""),
            "weighted_score": row.get("weighted_score", ""),
            "rank": row.get("rank", ""),
            "explanation": row.get("explanation", ""),
        })
    return PlainTextResponse(content=output.getvalue(), media_type="text/csv")
