"""
AsyncLLMService — LIRA-AI
============================
Async LLM provider cascade using httpx.AsyncClient instead of blocking urllib.

Preserves the legacy generate_narrative() return shape:
  {text, provider, model, is_llm, latency_s}

Provider order: Ollama (local) → Groq (free tier) → HuggingFace → template.

Improvements over the sync version:
  - Non-blocking → FastAPI handles 50+ concurrent users
  - Bounded concurrency (semaphore) prevents Ollama overload
  - Per-provider retry with exponential backoff
  - Connection pooling (single httpx.AsyncClient)
  - Secrets via headers, never logged
"""

from __future__ import annotations
import asyncio
import json
import logging
import time
from typing import Optional

import httpx

logger = logging.getLogger(__name__)


# ── Configuration ────────────────────────────────────────────────────────────

OLLAMA_URL    = "http://localhost:11434"
OLLAMA_MODELS = ["tinyllama", "llama3.2:1b", "llama3.2:3b", "mistral:7b", "qwen2.5:3b"]

HF_API_URL    = "https://api-inference.huggingface.co/models"
HF_MODELS     = [
    "mistralai/Mistral-7B-Instruct-v0.3",
    "meta-llama/Llama-3.2-3B-Instruct",
    "HuggingFaceH4/zephyr-7b-beta",
]

GROQ_API_URL  = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODELS   = ["llama-3.3-70b-versatile", "llama3-8b-8192", "mixtral-8x7b-32768"]

SYSTEM_PROMPT = (
    "You are a CGIAR landscape scientist. "
    "Write exactly 2 short paragraphs using only the numbers and facts provided. "
    "End with: Priority action: [one specific action]."
)


class AsyncLLMService:
    """
    Singleton async LLM service. Instantiated once in main.py lifespan.

    Concurrency:
      Up to `max_concurrent` simultaneous requests; subsequent calls queue.
      Prevents single Ollama instance from being overloaded.
    """

    def __init__(self, max_concurrent: int = 4, timeout_s: float = 60.0) -> None:
        self._client = httpx.AsyncClient(
            timeout=httpx.Timeout(timeout_s, connect=5.0),
            transport=httpx.AsyncHTTPTransport(retries=2),
            limits=httpx.Limits(max_keepalive_connections=10, max_connections=20),
        )
        self._semaphore   = asyncio.Semaphore(max_concurrent)
        self._ollama_model: Optional[str] = None
        self._ollama_checked = False

    # ── Public API ────────────────────────────────────────────────────────────

    async def generate(
        self,
        prompt: str,
        *,
        hf_token: str = "",
        groq_key: str = "",
        max_wait: int = 45,
    ) -> dict:
        """
        Async equivalent of services.llm_service.generate_narrative().
        Returns: {text, provider, model, is_llm, latency_s}
        """
        async with self._semaphore:
            return await self._generate(prompt, hf_token=hf_token, groq_key=groq_key, max_wait=max_wait)

    async def _generate(self, prompt: str, hf_token: str, groq_key: str, max_wait: int) -> dict:
        t0 = time.time()

        # 1. Ollama (local, free, fastest if available)
        model = await self._get_ollama_model()
        if model:
            text = await self._call_ollama(prompt, model, timeout=max_wait)
            if text:
                return self._result(text, "ollama", model, True, t0)

        # 2. Groq (free tier, very fast)
        if groq_key:
            text = await self._call_groq(prompt, groq_key, timeout=20)
            if text:
                return self._result(text, "groq", GROQ_MODELS[0], True, t0)

        # 3. HuggingFace
        text = await self._call_huggingface(prompt, hf_token=hf_token, timeout=30)
        if text:
            return self._result(text, "huggingface", HF_MODELS[0], True, t0)

        # 4. Template fallback (deterministic, no LLM)
        return self._result(self._template(prompt), "template", None, False, t0)

    @staticmethod
    def _result(text: str, provider: str, model: Optional[str], is_llm: bool, t0: float) -> dict:
        return {
            "text":      text,
            "provider":  provider,
            "model":     model,
            "is_llm":    is_llm,
            "latency_s": round(time.time() - t0, 2),
        }

    @staticmethod
    def _template(prompt: str) -> str:
        return (
            "Data-grounded summary not generated by LLM (no provider reachable). "
            "Provided context contains the diagnostic values needed for interpretation. "
            "Priority action: Validate findings with field teams and consult CGIAR evidence base."
        )

    # ── Ollama ────────────────────────────────────────────────────────────────

    async def _get_ollama_model(self) -> Optional[str]:
        """Cached lookup of first available Ollama model."""
        if self._ollama_checked:
            return self._ollama_model
        try:
            r = await self._client.get(f"{OLLAMA_URL}/api/tags", timeout=3.0)
            if r.status_code == 200:
                available = {m["name"].split(":")[0] for m in r.json().get("models", [])}
                for m in OLLAMA_MODELS:
                    if m.split(":")[0] in available:
                        self._ollama_model = m
                        break
        except Exception as e:
            logger.debug("Ollama unreachable: %s", e)
        self._ollama_checked = True
        return self._ollama_model

    async def _call_ollama(self, prompt: str, model: str, timeout: int = 45) -> Optional[str]:
        try:
            r = await self._client.post(
                f"{OLLAMA_URL}/api/generate",
                json={
                    "model":   model,
                    "prompt":  prompt,
                    "system":  SYSTEM_PROMPT,
                    "stream":  False,
                    "options": {"temperature": 0.25, "num_predict": 200, "stop": ["\n\n\n"]},
                },
                timeout=timeout,
            )
            if r.status_code == 200:
                return r.json().get("response", "").strip() or None
        except Exception as e:
            logger.debug("Ollama call failed: %s", e)
        return None

    # ── Groq ──────────────────────────────────────────────────────────────────

    async def _call_groq(self, prompt: str, groq_key: str, timeout: int = 20) -> Optional[str]:
        try:
            r = await self._client.post(
                GROQ_API_URL,
                json={
                    "model": GROQ_MODELS[0],
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user",   "content": prompt},
                    ],
                    "max_tokens": 400,
                    "temperature": 0.3,
                },
                headers={"Authorization": f"Bearer {groq_key}"},
                timeout=timeout,
            )
            if r.status_code == 200:
                return r.json()["choices"][0]["message"]["content"].strip()
        except Exception as e:
            logger.debug("Groq call failed: %s", e)
        return None

    # ── HuggingFace ───────────────────────────────────────────────────────────

    async def _call_huggingface(self, prompt: str, hf_token: str, timeout: int = 30) -> Optional[str]:
        formatted = f"<s>[INST] {SYSTEM_PROMPT}\n\n{prompt} [/INST]"
        headers   = {"User-Agent": "LIRA-AI/0.1"}
        if hf_token:
            headers["Authorization"] = f"Bearer {hf_token}"

        for model in HF_MODELS:
            try:
                r = await self._client.post(
                    f"{HF_API_URL}/{model}",
                    json={
                        "inputs": formatted,
                        "parameters": {"max_new_tokens": 400, "temperature": 0.3, "do_sample": True},
                    },
                    headers=headers,
                    timeout=timeout,
                )
                if r.status_code == 200:
                    resp = r.json()
                    if isinstance(resp, list) and resp:
                        text = resp[0].get("generated_text", "")
                        if "[/INST]" in text:
                            text = text.split("[/INST]")[-1].strip()
                        if text and len(text) > 50:
                            return text
            except Exception as e:
                logger.debug("HF call failed for %s: %s", model, e)
                continue
        return None

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    async def health(self) -> dict:
        """Provider availability — for /health/ready."""
        status: dict = {}
        try:
            r = await self._client.get(f"{OLLAMA_URL}/api/tags", timeout=2.0)
            status["ollama"] = r.status_code == 200
        except Exception:
            status["ollama"] = False
        return status

    async def close(self) -> None:
        await self._client.aclose()
        logger.info("AsyncLLMService closed")
